### PR TITLE
Update version.rb

### PR DESCRIPTION
**Pull request by TK-23**
This PR updates the version of the urbanopt-reopt-gem to 0.1.1

### CODE REVIEW

**Comment by kflemin** [comment]
@TK-23, if this version has major or breaking changes that would no longer work with the previous version's dependencies, you should bump the version to 0.2.0 instead of 0.1.1.   

I also noticed that in your Gemfile, in the else statements on lines 49 and 61, you are pointing to develop branch of geojson and scenario gems...shouldn't you point to 0.2.0 versions of both of those gems instead?

thanks!

**Comment by TK-23** [comment]
@kflemin thanks! just made those changes

**Comment by kflemin** [comment]
thanks!

**Comment by kflemin** [comment]
@TK-23 let me know when you are done with all of the merges and i will release the gem.  thanks!

**Comment by TK-23** [comment]
updating version and gentile

**Pull request merged**
